sudo: required
osx_image: xcode9.2
os:
  - linux
  - osx

language: go
go:
  - 1.9

env:
  global:
    - PKG_CONFIG_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib/pkgconfig"
    - LD_LIBRARY_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib"
    - DYLD_LIBRARY_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib"
    - PATH="$PATH:$GOPATH/bin"
    - LIBRDKAFKA_VERSION=master

# Travis OSX worker has problems running our Go binaries for 1.7 and 1.8,
# workaround for now is to skip exec for those.

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - rm -rf tmp-build
  - bash mk/bootstrap-librdkafka.sh ${LIBRDKAFKA_VERSION} tmp-build

install:
  - $GOPATH/bin/dep ensure
  - go build -tags static ./...
