CassandraConfiguration:
  Hosts: "cassandrahost.com"
  Port:
  Username: "user"
  Password: "password"
  Keyspace: "keyspace"

PublishServerConfig:
  Address: "127.0.0.1:8096"

FrontendServerConfig:
  Address: "127.0.0.1:8080"