Cassandra:
  Hosts: "m360-cass-dev.lb.ytel.com"
  Port: 9042
  Username: "dialer"
  Password: "\\0b4s2ZRrVE?WZ.p"
  Keyspace: "message360"
  Timeout: 10
Appname: "LocalTestApp"
KafkaTopic: "inbox_ingest"
KafkaProducerConfig: 
  Config: 
  - "bootstrap.servers=172.21.8.21:9092"
  - "acks=0"
  - "retries=5"
  - "linger.ms=200"
  - "group.id=localtest"
  - "max.in.flight.requests.per.connection=3"
  - "compression.type=lz4"
  KeyEnabled: true
KafkaConsumerConfig: 
  Config: 
  - "bootstrap.servers=172.21.8.21:9092"
  - "acks=0"
  - "retries=5"
  - "linger.ms=200"
  - "group.id=localtest"
  - "max.in.flight.requests.per.connection=3"
  - "compression.type=lz4"
RedisConfiguration:
  ClientType: "normal"
  Master: "mymaster"
  Hosts: "localhost:6379"
  Password: ""
  DB: 0